graphConfiguration:
    location: /var/scigraph-services/graph
    neo4jConfig:
      dump_configuration : true
      dbms.pagecache.memory : 2G

    indexedNodeProperties:
      - label
    exactNodeProperties:
      - label

    curies:
        # Monarch-specific
        '': 'http://www.monarchinitiative.org/'
        'MONARCH': 'http://www.monarchinitiative.org/MONARCH_'
        'MonarchData': 'http://data.monarchinitiative.org/ttl/'
        'MonarchArchive': 'http://archive.monarchinitiative.org/ttl/'
        
        # other semantic-web items
        'Annotation': 'http://www.w3.org/ns/oa#Annotation'  # FIXME - i don't think we're using this
        'dc': 'http://purl.org/dc/elements/1.1/'
        'foaf': 'http://xmlns.com/foaf/0.1/'
        
        # ontologies
        'AQTLTrait': 'http://identifiers.org/animalqtltrait/'  # FIXME - should get integrated into Upheno
        'BFO': 'http://purl.obolibrary.org/obo/BFO_'
        'CHEBI' : 'http://purl.obolibrary.org/obo/CHEBI_'
        'CHR' : 'http://purl.obolibrary.org/obo/CHR_'  # chromosomes
        'CL' : 'http://purl.obolibrary.org/obo/CL_'  # cell types
        'CLO' : 'http://purl.obolibrary.org/obo/CLO_'  # cell lines
        'CMO' : 'http://purl.obolibrary.org/obo/CMO_'  # clinical measurements
        'DATA' : 'http://edamontology.org/data_'  # data artifacts
        'DC' : 'http://purl.obolibrary.org/obo/DC_'  # disease clusters (grouping categories for diseases)
        'DECIPHER' : 'http://purl.obolibrary.org/obo/DECIPHER_'  # disease
        'DOID': 'http://purl.obolibrary.org/obo/DOID_'  # disease
        'ECO': 'http://purl.obolibrary.org/obo/ECO_'  # evidence code
        'EFO' : 'http://www.ebi.ac.uk/efo/EFO_'  # experimental factors - all kinds of stuff
        'EOM' : 'http://purl.obolibrary.org/obo/EOM_'  # elements of morphology phentoypes
        'ERO' : 'http://purl.obolibrary.org/obo/ERO_'
        'faldo' : 'http://biohackathon.org/resource/faldo#'  # genomic feature properties
        'FBcv' : 'http://purl.obolibrary.org/obo/FBcv_'  # flybase CV (includes phenotypes)
        'FBbt': 'http://purl.obolibrary.org/obo/FBbt_'  # flybase anatomy
        'FBdv': 'http://purl.obolibrary.org/obo/FBdv_'  # flybase developmental stages
        'GENO': 'http://purl.obolibrary.org/obo/GENO_'  # genotype partonomy
        'GO' : 'http://purl.obolibrary.org/obo/GO_'  # gene ontology
        'HP': 'http://purl.obolibrary.org/obo/HP_'  # human phenotype ontology
        'IAO': 'http://purl.obolibrary.org/obo/IAO_'  # information artifact ontology
        'KEGG-ds' : 'http://purl.obolibrary.org/KEGG-ds_'  # kegg diseases
        'LPT': 'http://purl.obolibrary.org/obo/LPT_'  # livestock product traits
        'MA': 'http://purl.obolibrary.org/obo/MA_'  # mouse anatomy
        'MedGen' : 'http://www.ncbi.nlm.nih.gov/medgen/'  # a vocabulary - should this be in purl?
        'MESH': 'http://purl.obolibrary.org/obo/MESH_'  # medical diseases, phenotypes, and drugs
        'MP': 'http://purl.obolibrary.org/obo/MP_'  # mammalian phenotype
        'MPATH': 'http://purl.obolibrary.org/obo/MPATH_'  # mammalian pathology
        'NBO': 'http://purl.obolibrary.org/obo/NBO_'  # neurobehavior ontology
        'OBA': 'http://purl.obolibrary.org/obo/OBA_'  # biological attributes / traits
        'OBAN': 'http://purl.org/oban/'  # annotation model
        'OBI': 'http://purl.obolibrary.org/obo/OBI_'  # biomedical investigations
        'OBO': 'http://purl.obolibrary.org/obo/'  # all things in the OBO namespace
        'OIO': 'http://www.geneontology.org/formats/oboInOwl#'  # obo-specific annotation properties, like synonym types
        'OMIA' : 'http://purl.obolibrary.org/obo/OMIA_'  # animal diseases
        'OMIM' : 'http://purl.obolibrary.org/obo/OMIM_'  # human disease and variants
        'Orphanet' : 'http://www.orpha.net/ORDO/Orphanet_'  # human diseases
        'PATO': 'http://purl.obolibrary.org/obo/PATO_'  # phenotypic qualities
        'PCO': 'http://purl.obolibrary.org/obo/PCO_'  # TODO
        'PR': 'http://purl.obolibrary.org/obo/PR_'  # protein ontology
        'PW' : 'http://purl.obolibrary.org/obo/PW_'  # pathway ontology
        'RO': 'http://purl.obolibrary.org/obo/RO_'  # relationships
        'SIO' : 'http://semanticscience.org/resource/SIO_'  # information artifacts
        'SNOMED' : 'http://purl.obolibrary.org/obo/SNOMED_'  # diseases and phenotypes
        'SO' : 'http://purl.obolibrary.org/obo/SO_'  # sequence ontology
        'STATO': 'http://purl.obolibrary.org/obo/STATO_'  # statistics ontology
        'UBERON' : 'http://purl.obolibrary.org/obo/UBERON_'  # integrated anatomy ontology (metazoans, mostly)
        'UPHENO' : 'http://purl.obolibrary.org/obo/UPHENO_'  # integrated phenotype ontology, and normal traits
        'UMLS' : 'http://purl.obolibrary.org/obo/UMLS_'  # unified medical language system
        'UO' : 'http://purl.obolibrary.org/obo/UO_'  # units of measurements
        'VT' : 'http://purl.obolibrary.org/obo/VT_'  # vertebrate traits
        'WBPhenotype': 'http://purl.obolibrary.org/obo/WBPhenotype_'  # worm (nematode) phenotypes
        'XCO' : 'http://purl.obolibrary.org/obo/XCO_'  # TODO
        'ZFA': 'http://purl.obolibrary.org/obo/ZFA_'  # zebrafish anatomy
        'ZFS': 'http://purl.obolibrary.org/obo/ZFS_'  # zebrafish staging
        'ZP': 'http://purl.obolibrary.org/obo/ZP_'  # zebrafish phenotype
        
        # publication/reference sources
        'DOI' : 'http://dx.doi.org/'
        'GeneReviews' : 'http://www.ncbi.nlm.nih.gov/books/'  # diseases too
        'ISBN': 'http://www.monarchinitiative.org/ISBN_'
        'ISBN-10': 'http://www.monarchinitiative.org/ISBN10_'
        'ISBN-13': 'http://www.monarchinitiative.org/ISBN13_'
        'ISBN-15': 'http://www.monarchinitiative.org/ISBN15_'
        'J' : 'http://www.informatics.jax.org/reference/J:'  # MGI-internal identifiers for pubs
        'MPD':  'http://phenome.jax.org/'
        'MPD-assay': 'http://phenome.jax.org/db/qp?rtn=views/catlines&keymeas='
        'PMID': 'http://www.ncbi.nlm.nih.gov/pubmed/'
        'PMCID' : 'http://www.ncbi.nlm.nih.gov/pmc/'
        'AQTLPub' : 'http://www.animalgenome.org/cgi-bin/QTLdb/BT/qabstract?PUBMED_ID='
        'GO_REF' : 'http://www.geneontology.org/cgi-bin/references.cgi#GO_REF:'
        'HPO' : 'http://human-phenotype-ontology.org/'  # to be used for persons, though they don't resolve with this
        
        # strains, lines, or organismal reagents
        'APB': 'http://pb.apf.edu.au/phenbank/strain.html?id='
        'CMMR': 'http://www.cmmr.ca/order.php?t=m&id='
        'Coriell' : 'https://catalog.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref='
        'CoriellCollection' : 'https://catalog.coriell.org/1/'
        'CoriellFamily' : 'https://catalog.coriell.org/0/Sections/BrowseCatalog/FamilyTypeSubDetail.aspx?fam='
        'CoriellIndividual' : 'https://catalog.coriell.org/Search?q='
        'dbSNPIndividual' : 'http://www.ncbi.nlm.nih.gov/SNP/snp_ind.cgi?ind_id='  # FIXME
        'EMMA' : 'https://www.infrafrontier.eu/search?keyword=EM:'
        'JAX' : 'http://jaxmice.jax.org/strain/'
        'MMRRC' : 'https://www.mmrrc.org/catalog/sds.php?mmrrc_id='
        'MPD-strain':  'http://phenome.jax.org/db/q?rtn=strains/details&strainid='
        'MUGEN': 'http://bioit.fleming.gr/mugen/Controller?workflow=ViewModel&expand_all=true&name_begins=model.block&eid='
        'NCIMR': 'https://mouse.ncifcrf.gov/available_details.asp?ID='
        'RBRC': 'http://www2.brc.riken.jp/lab/animal/detail.php?brc_no=RBRC'
        
        # organisms and genome builds  (also NCBITaxon)
        'NCBIAssembly': 'http://www.ncbi.nlm.nih.gov/assembly/'
        'NCBIGenome' : 'http://www.ncbi.nlm.nih.gov/genome/'
        'NCBITaxon' : 'http://purl.obolibrary.org/obo/NCBITaxon_'
        'OMIA-breed': 'http://monarchinitiative.org/model/OMIA-breed:'
        'UCSC' : 'ftp://hgdownload.cse.ucsc.edu/goldenPath/'
        
        # homology
        'HOMOLOGENE' : 'http://www.ncbi.nlm.nih.gov/homologene/'
        'KEGG-ko' : 'http://www.kegg.jp/dbget-bin/www_bget?ko:'
        'PANTHER' : 'http://www.pantherdb.org/panther/family.do?clsAccession='   # protein/orthologous families
        
        # variants
        'AQTL' : 'http://identifiers.org/animalqtl/'  # FIXME temporary  # traits
        'CGD' : 'http://ohsu.edu/cgd/'  # diseases, variant instances
        'ClinVar' : 'http://www.ncbi.nlm.nih.gov/clinvar/'  # variant+condition
        'ClinVarVariant' : 'http://www.ncbi.nlm.nih.gov/clinvar/variation/'
        'COSMIC' : 'http://cancer.sanger.ac.uk/cosmic/mutation/overview?id='
        'HGMD' : 'http://identifiers.org/hgmd/'
        'dbSNP' : 'http://www.ncbi.nlm.nih.gov/SNP/'
        'dbVar' : 'http://www.ncbi.nlm.nih.gov/dbvar/'
        
        # pathways
        'KEGG-path' : 'http://www.kegg.jp/dbget-bin/www_bget?path:'
        'REACT' : 'http://www.reactome.org/PathwayBrowser/#REACT_'
        
        # genes (and RNAs and transcripts)
        'BIOGRID' : 'http://thebiogrid.org/'  # also interactions
        'CCDS' : 'http://www.ncbi.nlm.nih.gov/CCDS/CcdsBrowse.cgi?REQUEST=CCDS&DATA='  # transcripty things
        'dictyBase' : 'http://dictybase.org/gene/'
        'EcoGene' : 'http://ecogene.org/gene/'
        'ENSEMBL' : 'http://identifiers.org/ensembl/'
        'FlyBase' : 'http://identifiers.org/FB:'  # also variants, pubs, genotypes, strains
        'GenBank' : 'http://www.ncbi.nlm.nih.gov/nuccore/'
        'HGNC' : 'http://identifiers.org/hgnc/HGNC:'
        'IMPC' : 'http://www.mousephenotype.org/data/genes/'  # FIXME
        'KEGG-hsa' : 'http://www.kegg.jp/dbget-bin/www_bget?hsa:'
        'MGI': 'http://www.informatics.jax.org/accession/MGI:'  # also variants, pubs, genotypes
        'miRBase' : 'http://identifiers.org/mirbase/'  # microRNA genes
        'NCBIGene' : 'http://www.ncbi.nlm.nih.gov/gene/'
        'PomBase' : 'http://identifiers.org/PomBase:'
        'RefSeq' : 'http://www.ncbi.nlm.nih.gov/refseq/?term='
        'RGD' : 'http://rgd.mcw.edu/rgdweb/report/gene/main.html?id='
        'SGD' : 'http://identifiers.org/SGD:'
        'TAIR' : 'http://identifiers.org/TAIR:'
        'WormBase' : 'http://identifiers.org/wormbase/'  # also variants, pubs, genotypes
        'Xenbase' : 'http://identifiers.org/xenbase/'
        'ZFIN' : 'http://zfin.org/'  # also variants, pubs, genotypes
        
        # proteins
        'EC' : 'http://identifiers.org/ec-code/'
        'HPRD' : 'http://www.hprd.org/protein/'
        'NCBIProtein' : 'http://www.ncbi.nlm.nih.gov/protein/'
        'PDB' : 'http://identifiers.org/PDB:'
        'SwissProt' : 'http://identifiers.org/SwissProt:'
        'TrEMBL' : 'http://www.uniprot.org/uniprot/'
        'UniProtKB' : 'http://identifiers.org/uniprot/'
        
        #chemicals
        'CID' : 'http://pubchem.ncbi.nlm.nih.gov/compound/'
        'DrugBank' : 'http://www.drugbank.ca/drugs/'
        

ontologies:
  - url: http://purl.obolibrary.org/obo/upheno/monarch.owl
    reasonerConfiguration:
      factory: org.semanticweb.elk.owlapi.ElkReasonerFactory
      addDirectInferredEdges: true
      addInferredEquivalences: true
      removeUnsatisfiableClasses: true
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/mgi_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/panther_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/clinvar_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/ncbigene_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/biogrid_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/zfin_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/ctd_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/hpoa_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/omim_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/coriell_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/hgnc_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/kegg_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/impc_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/ucscbands_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/monochrom.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/eom_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/genereviews_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/ensembl_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/orphanet_test.ttl
  - url: http://nif-crawler.neuinfo.org/monarch/ttl/animalqtldb_test.ttl

  - url: http://biohackathon.org/resource/faldo.ttl
  - url: http://evidenceontology.googlecode.com/svn/trunk/eco.owl
  - url: http://purl.obolibrary.org/obo/iao.owl
  - url: https://raw.githubusercontent.com/monarch-initiative/GENO-ontology/develop/src/ontology/geno.owl
  - url: http://purl.obolibrary.org/obo/ero.owl
  - url: http://purl.obolibrary.org/obo/pw.owl
  - url: https://raw.githubusercontent.com/jamesmalone/OBAN/master/ontology/oban_core.ttl
  # clo.owl is missing and import
  #- url: http://purl.obolibrary.org/obo/clo.owl
  - url: http://purl.obolibrary.org/obo/pco.owl
  - url: http://purl.obolibrary.org/obo/xco.owl
  - url: http://xmlns.com/foaf/spec/index.rdf
  - url: http://purl.org/dc/elements/1.1/
  - url: http://xmlns.com/foaf/0.1/

categories:
    http://purl.obolibrary.org/obo/CL_0000000 : cell
    http://purl.obolibrary.org/obo/UBERON_0001062 : anatomical entity
    #http://purl.obolibrary.org/obo/UBERON_0000468 : multi-cellular organism
    http://purl.obolibrary.org/obo/PATO_0000001 : quality
    #http://purl.obolibrary.org/obo/GO_0005623 : cell
    http://purl.obolibrary.org/obo/DOID_4 : disease
    #http://purl.obolibrary.org/obo/PATO_0000003 : assay
    #http://purl.obolibrary.org/obo/PATO_0000006 : process
    #http://purl.obolibrary.org/obo/PATO_0000011 : age
    #http://purl.obolibrary.org/obo/CHEBI_23367 : molecular entity
    http://purl.obolibrary.org/obo/CHEBI_23888 : drug
    http://purl.obolibrary.org/obo/UPHENO_0001001 : Phenotype
    #http://purl.obolibrary.org/obo/GO_0008150 : biological process
    #http://purl.obolibrary.org/obo/GO_0005575 : cellular component
    http://purl.obolibrary.org/obo/SO_0000704 : gene
    http://purl.obolibrary.org/obo/GENO_0000536 : genotype
    http://purl.obolibrary.org/obo/GENO_0000504 : reagent targeted gene
    #http://purl.obolibrary.org/obo/GENO_0000000 : intrinsic genotype
    #http://purl.obolibrary.org/obo/GENO_0000524 : extrinsic genotype
    #http://purl.obolibrary.org/obo/GENO_0000525 : effective genotype
    http://purl.obolibrary.org/obo/GENO_0000002 : variant locus
    http://purl.obolibrary.org/obo/SO_0001059 : sequence alteration
    http://purl.obolibrary.org/obo/SO_0000110 : sequence feature
    http://purl.obolibrary.org/obo/ECO_0000000 : evidence
    http://purl.obolibrary.org/obo/PW_0000001 : pathway

mappedProperties:
  - name: label
    properties:
    - http://www.w3.org/2000/01/rdf-schema#label
  - name: synonym
    properties:
    - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
    - http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym
    - http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym
    - http://purl.obolibrary.org/obo/go#systematic_synonym
    - http://ontology.neuinfo.org/NIF/Backend/OBO_annotation_properties.owl#synonym
  - name: acronym
    properties:
    - http://ontology.neuinfo.org/NIF/Backend/OBO_annotation_properties.owl#acronym
  - name: abbreviation
    properties:
    - http://ontology.neuinfo.org/NIF/Backend/OBO_annotation_properties.owl#abbrev
  - name: definition
    properties:
    - http://purl.obolibrary.org/obo/IAO_0000115
    - http://www.w3.org/2004/02/skos/core#definition
